name: redfin_views_analysis
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - ipython
    - matplotlib <= 3.4.3
    - numpy <= 1.21.4
    - pandas <= 1.3.4
    - pip
    - pymc3 <= 3.11.4
    - python <= 3.8
    - scipy <= 1.7.2
    - scikit-learn <= 0.24.2
    - statsmodels <= 0.13.1
    - pip:
      - uszipcode <= 0.2.6
