name: redfin_views_analysis
channels:
    - conda-forge
dependencies:
    - colorcet
    - jupyterlab
    - ipython
    - matplotlib
    - numpy <= 1.21.4
    - pandas
    - pip
   # - pymc
    - pymc3
    - python
    - scikit-learn
    - scipy <= 1.7.2
    - sqlalchemy
    - statsmodels
    - pip:
      - uszipcode <= 0.2.6
