name: redfin_views_analysis
channels:
    - conda-forge
dependencies:
    - colorcet
    - jupyter
    - ipython
    - matplotlib
    - numpy <= 1.19.5
    - pandas
    - pip
    - pymc3 <= 3.11.4
    - python
    - scikit-learn
    - scipy
    - sqlalchemy
    - statsmodels
